Repository koderDev/node.js-programs, pull requests merged in 2022-10, with the labels that each got.

#1 Add server.js
  Make a server/server.js
Labels: hacktoberfest, hacktoberfest-accepted

#2 Add createFile.js
  Create a file/createFile.js
Labels: hacktoberfest, hacktoberfest-accepted

#4 Add dt.js
  Date module, custom/dt.js
Labels: invalid, hacktoberfest, hacktoberfest-accepted

#5 Add file.js
  Read a file/file.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7 Add connect.js
  Connect to mySQL/connect.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#8 Add welcome.js
  Custom modules/welcome.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#9 Added Request logger
  middlewares/logger.js
Labels: hacktoberfest, hacktoberfest-accepted

#10 Added file to help users connect to mongoDB
  Connect to mongoDB/connect.js
Labels: hacktoberfest, hacktoberfest-accepted

#11 add nodejs mailgun send
  nodejs-send-mailgun/app.js
Labels: hacktoberfest, hacktoberfest-accepted

#12 add lambda function
  Lambda Function/index.js
Labels: hacktoberfest, hacktoberfest-accepted
